apiVersion: v1
kind: Pod
metadata: 
 name: config-pod
spec:
 name: nginx
 image: nginx
 env:
 - name: course
   valuefrom:
    congigMapKeyRef:
     name: course-config
     key: course
 - name: duration
   valuefrom:
    configMapKeyRef:
     name: course-config
     key: duration     